version: 2.1
jobs:
  test-checkout:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "test checkout"
          command: |
            echo "Vérifier la présence du code github"
            pwd
            ls -l 
            
workflows:
  test-checkout-workflow:
    jobs:
      - test-checkout
