version: 2.1

jobs:
  extraction:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      
  compilation:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: compilation
          command: echo "compilation du code"
      
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: test du code
          command: |
            ls -l 
            wc -l fichier.txt
            
workflows:
  checkout-test-workflow:
    jobs:
      - extraction
      - compilation:
          requires:
            - extraction
      - test:
          requires:
            - compilation
